name: EterEconomy
version: '${version}'

main: fr.eternom.eterEconomy.Main
api-version: '26.2'
load: POSTWORLD
authors: [ NadTum, JanjeVuk ]
description: Économie du réseau (soldes et banques), fournie à Vault. Commandes dans EterEssential.
depend: [EterLib, Vault]
